### ISSUE TITLE
Resolve `display: table` code smell on Company page

### ISSUE THREAD

**Issue by DivinoAG** [crystalhelix/companysite#41]
When using `display: block` for buttons on Company page, the `overflow: hidden` property causes the element to collapse vertically.

A temporary fix was made using `display: table` which makes the element work as intended, however it should not be required.

**Comment by natecox** [comment]
This is "resolved" by simply removing the `display: table` property, which seems to work across the board. 

@DivinoAG I'm closing this now, but we can reopen or open a new one if we feel that having nothing is also worthy of our attention.
